Update Recorded_Media_PTBR.txt
R4to0/ProjectZomboidTranslations pull request #12
Opened 2022-02-15 17:07 UTC by NaoEoGui

Exposure Survival Episódio 1

2022-02-15 17:27 UTC, NaoEoGui commented on PTBR/Recorded_Media_PTBR.txt
> +RM_d105d0be-6112-4937-a05c-c73bf5c98db4 = "Se tiver iscas, ou talvez peixes menores - ei?"
@Welenkens Não entendi essa frase.

2022-02-17 01:31 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_d105d0be-6112-4937-a05c-c73bf5c98db4 = "Se tiver iscas, ou talvez peixes menores - ei?"
Aqui temos um encontro de dois termos técnicos de Pescaria: _bait_ e _lure_. Em português, provavelmente seria generalizado.

- **Bait:** Iscas geralmente vivas e orgânicas.
- **Lure:** Iscas artificiais.

Or there's lures, or maybe smaller fish - ey
**Ou tenha iscas artificiais, ou talvez peixes pequenos, hein?**

2022-02-21 02:16 UTC, Welenkens requested changes
Primeira revisão.

2022-02-21 02:16 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_2513706b-56b2-4a2e-b695-c435cd5db1da = "Se você está longe de um rio e não há torneira?"
**E se você estiver** longe de um rio e **onde** não há torneira?

2022-02-21 02:16 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_c22d8eae-5dfe-48d0-8a33-a121ecb38411 = "Estou falando de chuva pessoal."
Estou falando de **chuva, pessoal.**

2022-02-21 02:16 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_6abcbf2d-04cf-41c8-8323-f276644b7c9a = "Pegue quatro tábuas de madeira, quatro pregos e..."
**Pegue quatro tábuas, quatro pregos e...**

2022-02-21 02:16 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_7c56d5aa-d3e5-4d74-baad-247854232362 = "Bata nelee com seu martelo."
Bata **neles** com seu martelo.

2022-02-21 02:16 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1a34010d-fb04-4fcd-becb-a19b40ab634d = "Em seguida, use sacos ou 'sacos de lixo', para o interior."
Em seguida, **use sacos de lixo** para o interior.

Aqui parece que foi feito um trocadilho...
_Rubbish_ é lixo no inglês britânico.
_Garbage_ é lixo no inglês americano.
Mas é tudo a mesma coisa.

2022-02-21 02:16 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1d6d143f-66c7-40c0-a0d6-96b9c1cf7414 = "Você vai pensar: 'Uau. eu não vou morrer.""
Você vai pensar: **"Uau. Eu não vou morrer."**

2022-02-21 02:16 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_dcfc3bbe-f4b7-4f07-8640-b6a418926b5b = ""E isso é incrivel!""
"E isso é **incrível**!"

2022-02-21 09:17 UTC, NaoEoGui commented on PTBR/Recorded_Media_PTBR.txt
> +RM_a86ded15-a68e-46ad-ab8d-794f4ff03edf = "A vida não é tudo... Coke Floats e rir à toa."
Eu pensava que era uma expressão tipo aquela "A vida não é só cola cola não" kllkk

2022-02-21 21:56 UTC, Welenkens approved these changes
Segunda revisão.

2022-02-21 21:56 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_12f9ad2b-4b62-45a5-b70b-ebbfc1fc4380 = "Mantenha-as regadas, não os pise nelas..."
Mantenha-as regadas, **não pise nelas...**

2022-02-21 21:56 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_975feaa4-ec5e-456c-9857-2028475a606a = "Armazenar chuva, ou 'água, é essencial para a sobrevivência."
Armazenar chuva, ou **'água'**, é essencial para a sobrevivência.

2022-02-21 21:56 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_7c56d5aa-d3e5-4d74-baad-247854232362 = "Bata neles com seu martelo."
**Coloque seu martelo em ação.**

- A frase fica mais natural dessa forma.

2022-02-21 21:56 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_6b9028c8-632d-494c-a18b-c161ebc0f1a8 = "E quando pegar o que puder encontrar?"
**E quando você tiver pegado o que pode encontrar?**

2022-02-21 21:56 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_6b76422e-3aaa-4670-a378-7ed53cdcad01 = "Bem, isso é incrível, hein?"
Bem, isso é incrível, **né?**

2022-02-21 22:42 UTC, merged