Update Recipes_PTBR.txt
R4to0/ProjectZomboidTranslations pull request #20
Opened 2022-03-12 13:40 UTC by NaoEoGui

Recipes Parte 1

2022-03-15 04:15 UTC, Welenkens requested changes
Primeira revisão

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Squid_Calamari = "Fazer Lula Calamari",
**Fazer Lula**

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Spoon = "Fazer Colher",
**Criar** Colher

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Newspaper_Hat = "Fazer Chapéu de Jornal",
**Criar** Chapéu de Jornal

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Noise_Maker = "Fazer Gerador de Ruído",
**Criar** Gerador de Ruído

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Paperclips = "Fazer Clipes de Papel",
**Criar** Clipes de Papel

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Pan = "Fazer Panela",
**Criar** Panela

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Pipe_bomb = "Fazer Bomba de Cano",
**Criar** Bomba de **Tubo**

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Plantain_Poultice = "Fazer Pomada de Banana",
Fazer **Cataplasma** de **Tanchagem**

- _Plantain_ se refere a uma planta medicinal muito popular chamada **Tanchagem**.

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Pot_of_Soup = "Fazer Pote de Sopa",
Fazer **Panela** de Sopa

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Remote_Controller_V1 = "Fazer Controle Remoto V1",
**Criar** Controle Remoto V1

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Remote_Controller_V2 = "Fazer Controle Remoto V2",
**Criar** Controle Remoto V2

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Remote_Controller_V3 = "Fazer Controle Remoto V3",
**Criar** Controle Remoto V3

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Remote_Trigger = "Fazer Gatilho Remoto",
**Criar** Gatilho Remoto

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Splint = "Fazer Tala",
**Criar** Tala

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Snare_Trap = "Fazer Armadilha de Laço",
**Criar** Armadilha de Laço

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Smoke_Bomb = "Fazer Bomba de Fumaça",
**Criar** Bomba de Fumaça

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Small_Metal_Sheet = "Fazer Placa de Metal Pequena",
**Criar** Placa de Metal Pequena

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Sledgehammer = "Fazer Marreta",
**Criar** Marreta

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Roasting_Pan = "Fazer Assadeira",
**Criar** Assadeira

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Saucepan = "Fazer Caçarola",
**Criar Panela**

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Shovel = "Fazer Pá",
**Criar** Pá

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Shotgun_Shells_Mold = "Fazer Molde de Rartuchos de Espingarda",
**Criar** Molde de **Munição** de Espingarda

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Shotgun_Shells = "Fazer Cartuchos de Espingarda",
**Criar Munição** de Espingarda

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Saw = "Fazer Serra",
**Criar** Serra

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Scissors = "Fazer Tesoura",
**Criar** Tesoura

2022-03-15 04:15 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Sheet_Metal = "Fazer Chapa Metálica",
**Criar Placa de Metal**

2022-03-21 21:28 UTC, R4to0 commented
Deletando alguns comentários/reviews pra ver se soluciona o problema de não carregar o arquivo.

2022-03-25 21:33 UTC, Welenkens approved these changes

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Add_Crafted_Trigger = "Adicionar Gatilho Criado",
Adicionar **Acionador Artesanal**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Attach_Hand_Fork_to_Spear = "Colocar Garfo de Mão na Lança",
Colocar **Garfo de Jardinagem** na Lança

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Craft_Makeshift_Radio = "Fazer Rádio Improvisado",
**Criar** Rádio Improvisado

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Dismantle_Earbuds = "Desmontar Fones de Ouvido",
Desmontar **Fone** de Ouvido

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Dismantle_Headphones = "Desmontar Headphones",
Desmontar **Headphone**

- _Headphone_: apenas fone
- _Headset_: fone e microfone

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +	Recipe_HotDrinkRed = "Fazer Bebida Quente na Caneca Vermelha",
**Fazer Bebida Quente**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +	Recipe_HotDrinkSpiffo = "Fazer Bebida Quente na Caneca Spiffo",
**Fazer Bebida Quente**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +	Recipe_HotDrinkWhite = "Fazer Bebida Quente na Caneca Branca",
**Fazer Bebida Quente**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Remote_Trigger = "Criar Gatilho Remoto",
Criar **Acionador** Remoto

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Squid_Calamari = "Fazer Lula Calamari",
**Fazer Lula**

_Calamari_ = Lula

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Stone_Hammer = "Criar Mrtelo de Pedra",
Criar **Martelo** de Pedra

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Suture_Needle_Holder = "Criar Suporte de Agulha de Sutura",
**Criar Porta Agulha**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Make_Tent_Kit = "Criar Kit Barraca",
Criar Kit **de** Barraca

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Open_Canned_Bolognese = "Abrir Lata de Espaguete à Bolonhesa",
Abrir Lata de **Espaguete Bolonhesa**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Open_Canned_Corned_Beef = "Abrir Lata de Salada de Frutas",
Abrir Lata de **Carne**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Place_Rice_in_Cooking_Pot = Colocar Arroz na Panela",
Colocar Arroz na **Panela Grande**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Place_Pasta_in_Cooking_Pot = "Colocar Macarrão na Panela",
Colocar Macarrão na Panela **Grande**

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Reclaim_Butter_Knife_from_Spear = "Retirar a Faca de Manteiga da Lança",
**Retirar Faca** de Manteiga da Lança

2022-03-25 21:33 UTC, Welenkens commented on PTBR/Recipes_PTBR.txt
> +    Recipe_Slice_Fillet = "Extrair Filé",
**Fatiar** Filé

2022-03-26 03:02 UTC, Welenkens approved these changes

2022-03-26 07:47 UTC, R4to0 approved these changes

2022-03-28 02:32 UTC, merged