Update Stash_PTBR.txt
R4to0/ProjectZomboidTranslations pull request #22
Opened 2022-03-15 18:32 UTC by NaoEoGui

Stash Parte 1

2022-03-17 22:32 UTC, Welenkens requested changes

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MulMap7_Text3 = "fodido",
**ferrado**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MulMap8_Text1 = "Pegue minhas coisas. Me enterre se puder e se for seguro. Deus te abençoê.",
Pegue minhas coisas. **Enterre-me se puder e for seguro. Deus te abençoe.**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MulMap10_Text1 = "casa da morte",
**casa com cadáver**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MulMap10_Text3 = "parecia claro por aqui",
parecia **limpo** por aqui

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MulMap12_Text2 = "médico bosta",
**itens médicos**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MulMap13_Text2 = "muito equipamento ainda na loja de hardwares",
muito equipamento ainda na loja de **ferramentas**

- _Hardware store_: Loja de ferramentas

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap1_Text1 = "Claro que era aqui que ele morava",
**Tenho certeza** que era **onde** ele morava

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap4_Text1 = "Seja corajoso. Eu amo você.",
Seja corajoso. **Eu te amo.**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap4_Text3 = "NÃO VÁ AQUI. Megan está aqui em algum lugar – ela é uma deles.",
NÃO VÁ AQUI. Megan está aqui em algum lugar – ela é **um** deles.

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap4_Text31 = "Nem sabia que ela estava na cidade. Só não vá",
Nem sabia que ela estava na cidade. **Apenas** não vá

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap6_Text3 = "inferno aquecido",
**calor infernal**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap8_Text3 = "viu um cara morrer",
**vi** um cara morrer

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap9_Text1 = "buraco do inferno de zumbis",
**maldita toca de zumbis**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap10_Text1 = "todos os tipos de merda",
**todo tipo** de merda

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap10_Text2 = "loja de hardwares ainda pode ter coisas",
**a** loja de **ferramentas** ainda pode ter coisas

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap11_Text11 = "O filho da puta louco sabia o que estava por vir.",
**Aquele louco filho da puta** sabia o que estava por vir.

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap11_Text2 = "Local de hardware intocado.",
**Loja de ferramentas intacta.**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap12_Text1 = "todos chegaram ao seu trabalho no dia em que a febre atingiu",
todos chegaram **no trabalho** no dia em que a febre **explodiu**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap12_Text11 = "Eu os abordei antes que eles se virassem",
Eu os **hospedei** antes que eles **virassem**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_WpMap12_Text3 = "Black Friday meio que multidões",
**multidão de Black Friday**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap2_Text1 = "te deixou uma pistola",
te **deixei** uma pistola

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap2_Text2 = "loja. Parecia que tinha suprimentos",
**a loja parecia ter suprimentos**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap2_Text3 = "eles migram? Parece que eles estavam vindo aqui",
eles migram? Parece que eles estavam **indo para cá**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap4_Text1 = "Se você pode fazer isso antes de virar. Há algo aqui para ajudar.",
**Se você conseguir fazer isso antes de virar.** Há algo aqui para ajudar.

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap4_Text2 = "Centro Comunitário. Você encontrará meu corpo aqui. Eu amo você.",
Centro Comunitário. Você encontrará meu corpo aqui. **Eu te amo**.

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap4_Text3 = "Desejo a Deus que você nunca tivesse sido colocado aqui. Boas lembranças aqui.",
**Desejo a Deus que nunca tivesse sido colocado aqui. Apesar de boas lembranças.**

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap5_Text1 = "não use armas - coisas que você pode usar como armas aqui",
não use **armas de fogo** - coisas que você pode usar como armas aqui

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap6_Text2 = "hardware extra",
**ferramenta** extra

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap6_Text3 = "inferno vazio aqui",
**bem** vazio aqui

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap7_Text2 = "Você provavelmente precisará ser preparado",
Você provavelmente precisará **estar** preparado

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_RosewoodStashMap3_Text1 = "Fui e encontrei alguns equipamentos para nos ajudar a fortificar algum lugar enquanto esperamos.",
Foi e encontrou **alguns equipamentos** para nos ajudar a fortificar algum lugar enquanto esperamos.

2022-03-17 22:32 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_RosewoodStashMap3_Text11 = "Antiga casa da mamãe. te vejo lá x",
Antiga casa da mamãe. te vejo lá **bjs**

2022-03-18 17:50 UTC, Welenkens approved these changes

2022-03-18 17:50 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap2_Text3 = "eles migram? Parece que eles estavam indo para cá",
eles migram? Parece que eles estavam **vindo pra** cá

2022-03-18 17:50 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MarchRidgeMap4_Text1 = "Se você conseguir fazer isso antes de virar. Há algo aqui para ajudar.",
Se você conseguir fazer isso antes de **virar...** Há algo aqui para ajudar.

2022-03-18 17:50 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_RosewoodStashMap3_Text11 = "Antiga casa da mamãe. te vejo lá bjs",
Antiga casa da mamãe. **Te** vejo lá bjs

2022-03-21 21:09 UTC, Welenkens approved these changes

2022-03-21 21:09 UTC, Welenkens commented on PTBR/Stash_PTBR.txt
> +    Stash_MulMap12_Text1 = "espingarda aqui - comida na cozinha?.",
espingarda aqui - comida na **cozinha?**

- Não se aplica ponto final após "!" ou "?".

2022-03-22 00:50 UTC, NaoEoGui commented on PTBR/Stash_PTBR.txt
> +    Stash_MulMap12_Text1 = "espingarda aqui - comida na cozinha?.",
Eu tlgd é que eu n vi mesmo x'D

2022-03-22 05:38 UTC, merged