Update Recorded_Media_PTBR.txt
R4to0/ProjectZomboidTranslations pull request #6
Opened 2022-02-02 23:41 UTC by NaoEoGui

2022-02-05 18:36 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_ef90911d-ded7-46ef-8370-6761fa46dbf1 = "Vocês estão assistindo Artesanato de Madeira!"
Artesanato **em** Madeira

2022-02-05 18:44 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_cfe20d50-cb0e-46f7-82f6-1810fccc3ede = "Ok então estamos falando com homens hoje, aparentemente."
Sinta-se livre para fazer mudanças gramáticas que favoreçam a leitura. É interessante que a pessoa ao ler, realmente consiga imaginar o cenário como um verdadeiro programa de televisão
.
**Ok! Então** estamos falando com homens hoje, aparentemente.

2022-02-05 18:46 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_2991fa22-771d-49b4-8da5-7a48fd3ae9f4 = "Eles dizem que você realmente faria. Então... ao trabalho."
[...] realmente **gostaria**.

2022-02-05 18:54 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1412f5c4-3f1f-487c-ae8a-5ee37a33b91e = "Yee-hah. E ai estão vocês."
A expressão **Yee-hah** curiosamente, em português, geralmente traduziríamos com **irra**, porém, essa interjeição teria um significado contrário ao que infere **Yee-hah**. No caso, acredito que poderíamos optar por **Isso aí!**

**Isso aí**! E **aí** estão vocês.

2022-02-05 18:55 UTC, NaoEoGui commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1412f5c4-3f1f-487c-ae8a-5ee37a33b91e = "Yee-hah. E ai estão vocês."
Tava procurando essa expressão mas não estava lembrando kkkk vou optar por ela sim

2022-02-05 19:06 UTC, NaoEoGui commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1412f5c4-3f1f-487c-ae8a-5ee37a33b91e = "Yee-hah. E ai estão vocês."
Também optei por outros tipos que nos usamos como: Uhull, Iupi e irra

2022-02-05 19:16 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_c3107705-b4bd-4372-a444-a99a8a1a7ab3 = "Junte tudo e... você está bem e pronto."
Junte tudo e... você está **indo** bem e pronto.

2022-02-05 19:18 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1899fcc0-f1c3-4ee7-87e0-8dcb27805977 = "Bem, Eu preciso de uma cerveja."
Bem, Eu preciso de uma **bebida**.

2022-02-05 19:25 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_7c0b406b-7df4-48eb-8b5e-6c9c2d386cfc = "Pega uma tábua e um prego assim..."
**Pegue** uma tábua e um prego assim...

2022-02-05 19:26 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_e45c055b-f1e8-4d61-8b0e-34f294fb1f56 = "Ficou bem legal assim né?"
Ficou bem legal assim, **hein**?

2022-02-05 19:29 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_708016fa-a53f-4587-8152-b8137bab2108 = "Sabe o que mais é bom na prática?"
Sabe o que mais é bom **para praticar**?

2022-02-05 19:37 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> -RM_85a375b9-7b8b-4c04-a165-f7dbb311c703 = "Hunk at work, maybe?"
_Hunk_ é um termo digamos que... voltado à questão de atração. Podemos perceber que o orientador dos programas de Artesanato em Madeira é uma pessoa muito bem humorada. Trata diversas situações com naturalidade e de forma lúdica. A tradução nesse caso seria algo como:

**Gostosão no trabalho**, talvez?
Porém, vamos optar por:
**Bonitão no trabalho**, talvez?

2022-02-05 19:38 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_85a375b9-7b8b-4c04-a165-f7dbb311c703 = "Bonito no trabalho, talvez?"
Hunk é um termo digamos que... voltado à questão de atração. Podemos perceber que o orientador dos programas de Artesanato em Madeira é uma pessoa muito bem humorada. Trata diversas situações com naturalidade e de forma lúdica. A tradução nesse caso seria algo como:

Gostosão no trabalho, talvez?
Porém, vamos optar por:
Bonitão no trabalho, talvez?

2022-02-05 19:42 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_bbf4a0b6-7055-4122-9433-ea40647ea926 = "Carpintaria intermediária! Yeehah!"
Carpintaria intermediária! **Isso aí!**

2022-02-05 19:42 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_b7e32974-8467-4965-82b5-c97ffccb1785 = "Cansado de ver o rosto do seu marido senhoras?"
Cansado de ver o rosto do seu marido**,** senhoras?

2022-02-05 19:47 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_7dc307e3-ec34-4180-ab3c-1e362f005d00 = "Legal né?"
Legal**, né**?

2022-02-05 19:51 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_9591ed45-41c4-4640-9368-c404344be186 = "Novas portas e janelas? Esse é o jogo final!"
*Agora* portas e janelas? Esse é o jogo final!

2022-02-05 19:53 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_d91f00c8-e0bc-4548-b102-a2722e8b1fca = "Há uma coisa que você pode fazer por eles agora, lembre-se..."
Há uma coisa que você pode fazer **para elas** agora, lembre-se...

2022-02-05 19:54 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1b6f4796-4cbf-48b9-940a-42ef3b5ab4d3 = "E isso é encontrar um lugar para pendurar."
E isso é encontrar um lugar para **colocá-las.**

2022-02-05 19:55 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_960545e8-d2ae-4e07-9d06-aa1fc4a8c002 = "Ai vai senhoras!"
**Aí** vai senhoras!

2022-02-05 19:57 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_cbddff21-3dc9-4bab-9d1b-751fca544a0b = "Mais uma diversão que tive com minha camisa!"
**A maior** diversão que tive **recentemente** com minha camisa!

2022-02-05 19:58 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_9ba099b3-120e-45fa-88b2-fef4c259223b = "No próximo programa - intermediária parte 2!"
No próximo programa - **Carpintaria** intermediária parte 2!

2022-02-05 20:08 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_226d1ba4-b0ae-4c95-a960-7b1e76909271 = "Encontramos um lugar onde você pode redefinir esse doce traseiro!"
Encontramos um lugar onde você pode **descansar seu belo traseiro!**

2022-02-05 20:09 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_0edc7b1d-9af1-4791-8529-f25d54f551b7 = "Episódios 4: Prateleiras e Cercas"
**Episódio** 4: Prateleiras e Cercas

2022-02-05 20:13 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_9515c597-8395-4047-844d-843f359719d9 = "Olá, todos da TV diurna. Isso não é um programa."
Olá, todos da TV diurna! **Não é minha chamada.**

2022-02-05 20:14 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_c436879b-7103-4fac-9760-095a1698558d = "Você usava essas calças bonitas e apertadas. Hein?"
Usava **aquelas** calças bonitas e apertadas. Hein?

2022-02-05 20:18 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_26d6fbe3-6fa0-4add-b3cd-9f0b4dc05739 = "Cinco tábuas! Quatro pregos! Yeehah!"
Cinco tábuas! Quatro pregos! Isso aí!

2022-02-05 20:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_7bb34ff8-504e-46d3-b51a-efdcdc9d8038 = "Um lugar para suas joias, suas preciosas coisas"
Um lugar para suas joias, suas preciosas coisas**?**

2022-02-05 20:47 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_b8960705-6bb2-424f-8b6d-ea7d22a83047 = "Oh ei, está cansado de pessoas vendo você tomar sol'?"
**Oh! Ei! Está** cansado de pessoas vendo você tomar sol?

2022-02-05 20:47 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_ba949727-2b3a-46ba-a75b-74af46c0b59a = "Eu também. Era o tempo inteiro."
Eu **estava**. Era o tempo inteiro.

2022-02-05 20:48 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_f7948221-372c-4c26-b14e-bf0867cc1316 = "Então eu construi uma cerca."
Então **construí** uma cerca.

2022-02-05 20:49 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_4ad36743-ad25-4116-b35e-df46a927ae10 = "Então se você me der licença, Eu vou apenas..."
Então se **me** der licença, **vou** apenas...

2022-02-05 20:50 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_5f7b7bf7-7439-40ac-a3f4-1ac739931045 = "Fique confortavel sem minha camisa..."
**Ficar confortável** sem minha camisa...

2022-02-05 22:00 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_cad9e8aa-1f6c-4e47-a588-430fb43287df = "Posso ouvir um iupii?"
Posso ouvir um **'Uhu'**?

**Iupi** não está errado, mas me parece mais infantil.

2022-02-05 22:26 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_6284a71c-25d1-46bf-9f52-4600993c6117 = "Os livros precisam de estantes, então proximo passo: uma estante."
Os livros precisam de estantes, então **próximo** passo: uma estante.

2022-02-05 23:19 UTC, Welenkens requested changes
Revisão finalizada. Aguardarei as alterações para uma segunda revisão definitiva. Desde já agradeço.

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_7611b105-5e53-41f2-8b14-e4b06aec4fb8 = "...e elas estão sorrindo mais ainda quando descem."
**e sorrindo mais ainda quando descem.**

Em inglês é comum ter essa redundância nas frases, mas em português isso naturalmente é suprimido.

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_ae242595-b86e-4c88-9d7c-73d32a15f3a8 = "Uma mesa com uma gaveta, certo? Isso faz você um iupii?"
Uma mesa com uma gaveta, certo? **Isso te deixa animado?**

Nessa parte é interessante mudar um pouco. Uma tradução ao pé da letra deixa um sentido estranho.

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_3ecc9bdb-66a9-422b-a259-01958917da40 = "Me faz iupii de qualquer maneira."
Me **deixa animado** de qualquer maneira.

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_4650481b-66ce-4450-aab5-cbba35f9f1e9 = "Cinco tábuas! Quatro pregos! Vai!"
Cinco tábuas! Quatro pregos! **Vamos lá!**

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_8d3e42db-0a5f-4aa1-ad36-bcec0df8a0dd = "DUAS TÁBUAS! QUATRO PREGOS! VAI!"
DUAS TÁBUAS! QUATRO PREGOS! **VAMOS LÁ**!

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_c3680f0b-6618-49ff-9cc9-46454913c1a5 = "Talvez uma bíblia, talvez uma arma."
Talvez uma **Bíblia**, talvez uma arma.

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_ba949727-2b3a-46ba-a75b-74af46c0b59a = "Eu estava. Era o tempo inteiro."
Eu estava. Era o tempo **todo**.

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_bc33e81d-30f1-43a3-b4f0-bb039a3a1207 = "Episódio 5: Porta"
"Episódio 5: **Portas**"

Os títulos geralmente estão no plural.

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_31f0e287-8144-4d80-b1c2-5fce7c7245e8 = "Bem olá! Vocês acabaram de me pegar malhando!"
"**Bem, olá**! Vocês acabaram de me pegar malhando!"

A vírgula é importante aqui. Imaginamos que ele está malhando e subitamente inicia o programa. É como se expressasse de maneira surpresa no início.

2022-02-05 23:19 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_ba8abeaf-af63-4fe0-8a2b-72610c608f46 = "Estou suando real aqui!"
Estou suando **muito** aqui!

2022-02-06 02:40 UTC, Welenkens requested changes
Pequenas alterações. Após as correções, essa parte pode ser considerada finalizada.

2022-02-06 02:40 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_c7bd1d0a-59fe-43ba-9510-fe8f7b6f86c0 = "Você vai precisar de cinto tábuas e quatro pregos."
Você vai precisar de **cinco** tábuas e quatro pregos.

2022-02-06 02:40 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_2991fa22-771d-49b4-8da5-7a48fd3ae9f4 = "Eles dizem que você realmente gostaria. Então... ao trabalho."
**Dizem** que você realmente gostaria. Então... ao trabalho.

2022-02-06 02:40 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1412f5c4-3f1f-487c-ae8a-5ee37a33b91e = "Irra. Aí estão vocês."
**Isso aí!** Aí estão vocês.

2022-02-06 02:40 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_9d6ef1e8-d22a-400d-ae48-fc1c019e3ccd = "Episódio 3: Molduras e paredes"
Episódio 3: Molduras e **Paredes**

2022-02-06 02:40 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_b8960705-6bb2-424f-8b6d-ea7d22a83047 = "Oh! Ei, está cansado de pessoas vendo você tomar sol'?"
Ei, está cansado de pessoas vendo você tomar **sol?** 

Há uma aspas simples perdida na frase.

2022-02-06 02:40 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_871ef7dc-7d44-45ee-a0f2-783b8fb5215b = "Episódio 1: Estante de Livros"
Episódio 1: **Estantes** de Livros

2022-02-06 02:40 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_19a4a3eb-ce84-4c1a-8ab8-9c9014609003 = "Molduras de janelas, molduras de portas... tudo a mesma coisa pra mim."
Molduras de janelas, molduras de portas... tudo a mesma coisa **para** mim.

2022-02-06 03:04 UTC, Welenkens approved these changes

2022-02-06 03:04 UTC, Welenkens commented on PTBR/Recorded_Media_PTBR.txt
> +RM_1e98f3bb-640d-42b8-8484-b47b1191799d = "Agora não leio livros, mas algumas pessoas sim."
**Não** leio livros, mas algumas pessoas sim.

2022-02-06 03:53 UTC, merged