Update ContextMenu_PTBR.txt
R4to0/ProjectZomboidTranslations pull request #8
Opened 2022-02-06 07:39 UTC by NaoEoGui

2022-02-07 23:30 UTC, Welenkens requested changes
Mudanças cruciais, estéticas e semânticas. 
Atente-se aos termos técnicos de acordo com o tema traduzido.

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_Unjam = "Desbloquear %1",
**Desemperrar** %1

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_UnloadRounds = "Descarregando %1",
**Desmuniciar** %1

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_Yourself = "Você mesmo",
Você **Mesmo**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_TrimBeard_For = "Cortando Barba %1",
**Cortar** Barba %1

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_CutHair = "Cortar o Cabelo",
**Cortar Cabelo**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_CutHairFor = "Cortando Cabelo %1",
**Cortar** Cabelo %1

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_UntieHair = "Desamarrar o Cabelo",
**Desamarrar Cabelo**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_TieHair = "Amarrando o Cabelo %1",
**Amarrar Cabelo** %1

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_ShaveHair = "Raspar o Cabelo",
**Raspar Cabelo**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_Attach = "Colocar",
**Equipar**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_ChangeFireMode = "Alterar modo de disparo",
Alterar **Modo** de **Disparo**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_FireMode_Single = "Individual",
**Semiautomático**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_FireMode_Auto = "Totalmente Automático",
**Automático**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_PatchAllHoles = "Remende Todos os Buracos usando ",
**Remendar todos** os Buracos usando

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_CantRemovePatch = "Agulha Necessária.",
Agulha **é necessária**.

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_AddPaddingAll = "Adicinar preenchimento em tudo usando ",
**Adicionar Preenchimento** em tudo usando

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_TieBandanaFace = "Por no rosto",
**Colocar** no rosto

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_DyeHair = "Pintar o Cabelo",
**Pintar Cabelo**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_DyeBeard = "Pintar a Barba",
**Pintar Barba**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_PutOnEartop = "Colocar em cima da orelha",
Colocar em **Cima** da **Orelha**

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_LeftMiddleFinger = "Colocar no Dedo do Meio Esquerdo",
Colocar no Dedo **Médio** Esquerdo

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_RightMiddleFinger = "Colocar no Dedo do Meio Direito",
Colocar no Dedo **Médio** Direito

2022-02-07 23:30 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_Vehicle_AttachTrailer2 = "Prender Reboque",
**Rebocar Trailer**

2022-02-10 01:28 UTC, Welenkens requested changes
Segunda revisão. Apenas alguns ajustes.
É possível que tenha novos ajustes de acordo com análises da interface do jogo.

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_Lamp_on_Pillar = "Lâmpada no Pilar",
**Poste de Iluminação Improvisado**

Lâmpada no Pilar fica muito "ao pé da letra".

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_Shelves = "Prateleiras",
**Prateleira**

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_DoubleShelves = "Prateleiras Duplas",
**Prateleira Dupla**

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_RemoveCharcoal = "Remover Carvão Vegetal",
**Remover Carvão**

É bom saber a diferença entre _coal_ e _charcoal_, que é carvão mineral e vegetal respectivamente.
No entanto, nesse caso, não há necessidade de especificar.

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_MetalShelves = "Prateleiras de Metal",
**Prateleira** de Metal

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_MetalCrate = "Caixote de Metal",
**Caixa** de Metal

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_PanicNoSleep = "Muito em pânico para dormir.",
**Em pânico demais** para dormir.

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_Double_Wooden_Door = "Porta Dupla de Madeira",
**Portão Duplo** de Madeira

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_Vehicle_AttachTrailer = "Rebocar<br>%1<br>to<br>%2",
Rebocar ... **em** ....

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_UnloadMagazine = "Descarregar Carregador",
**Desmuniciar** Carregador

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_CantRepair = "Tecido, agulha e linha necessários para o remendo de roupas.",
Tecido, agulha e linha **são** necessários para o remendo de roupas.

2022-02-10 01:28 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +    ContextMenu_Fitness = "Exercício",
**Exercitar-se**

2022-02-13 01:57 UTC, Welenkens requested changes
Alterações finais. Possíveis alterações ainda podem ser requisitadas mas após testes no jogo.

2022-02-13 07:49 UTC, NaoEoGui commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_NoSleepTooEarly = "Não consigo voltar a dormir.<br>Tente mais tarde.",
Então quando tiver o <br> é pq passa pra linha de baixo?

2022-02-14 23:56 UTC, Welenkens commented on PTBR/ContextMenu_PTBR.txt
> +	ContextMenu_NoSleepTooEarly = "Não consigo voltar a dormir.<br>Tente mais tarde.",
Sim. É da linguagem de programação. É muito comum em várias outras, HTML, por exemplo.
Isso vai acontecer dentro do jogo, no caso.

2022-02-17 01:36 UTC, merged